# Generated by Django 2.1.3 on 2018-11-18 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vitimas1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('sobrenome', models.CharField(max_length=60)),
                ('telefone', models.IntegerField(default=11)),
                ('email', models.EmailField(max_length=254)),
                ('senha', models.CharField(max_length=16)),
            ],
        ),
    ]
